# Generated by Django 6.1 on 2026-08-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Novo Pedido'), ('CONFIRM', 'Aguardando Confirmação'), ('PAYMENT', 'Aguardando Pagamento'), ('PAID', 'Pedido Pago'), ('PRODUCTION', 'Em Produção'), ('SENT', 'Pedido Enviado'), ('CANCELED', 'Pedido Cancelado'), ('DELIVERED', 'Pedido Entregue')], db_index=True, default='NEW', max_length=30, verbose_name='Status'),
        ),
    ]
