# Generated by Django 6.1 on 2026-09-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipping_price_order_shipping_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=60, verbose_name='Código de Rastreio'),
        ),
    ]
