# Generated by Django 6.1 on 2026-09-08 00:10

from django.db import migrations, models
from django.db.models import F


def backfill_verified_at(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_active=True, email_verified_at__isnull=True).update(
        email_verified_at=F("created_at")
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email verificado em'),
        ),
        migrations.RunPython(backfill_verified_at, noop),
    ]
