# Generated by Django 6.1 on 2026-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_nsfw',
            field=models.BooleanField(db_index=True, default=False, help_text='Conteúdo para maiores de 18 anos: exige verificação de idade e não é indexado.', verbose_name='+18'),
        ),
    ]
