# Generated by Django 6.1 on 2026-08-11 12:45

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='image',
            field=models.ImageField(upload_to='figures/', validators=[core.validators.validate_image_size], verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='figureimage',
            name='image',
            field=models.ImageField(upload_to='figures/gallery/', validators=[core.validators.validate_image_size], verbose_name='Imagem'),
        ),
    ]
