# Generated by Django 6.1 on 2026-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0002_alter_figure_image_alter_figureimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=5, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='figure',
            name='length_cm',
            field=models.DecimalField(decimal_places=1, default=15, max_digits=5, verbose_name='Comprimento (cm)'),
        ),
        migrations.AddField(
            model_name='figure',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0.3, max_digits=5, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='figure',
            name='width_cm',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=5, verbose_name='Largura (cm)'),
        ),
    ]
