# Generated by Django 6.1 on 2026-09-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0003_figure_height_cm_figure_length_cm_figure_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, default=60, max_digits=5, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='length_cm',
            field=models.DecimalField(decimal_places=1, default=35, max_digits=5, verbose_name='Comprimento (cm)'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=3, max_digits=5, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='width_cm',
            field=models.DecimalField(decimal_places=1, default=40, max_digits=5, verbose_name='Largura (cm)'),
        ),
    ]
