# Generated by Django 6.1 on 2026-09-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0004_alter_figure_height_cm_alter_figure_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='sold_out',
            field=models.BooleanField(default=False, verbose_name='Esgotado'),
        ),
    ]
