# Generated by Django 6.1 on 2026-09-06 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0005_figure_sold_out'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Registro Ativo')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('is_notified', models.BooleanField(db_index=True, default=False, verbose_name='Avisado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='figures.figure', verbose_name='Action Figure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Alerta de reposição',
                'verbose_name_plural': 'Alertas de reposição',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('figure', 'email'), name='unique_stock_alert_per_figure_email')],
            },
        ),
    ]
