# Generated by Django 6.1 on 2026-09-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0006_stockalert'),
        ('newsletters', '0002_move_stockalert_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockalert',
            name='figures_unique_stock_alert_per_figure_email',
        ),
        migrations.DeleteModel(
            name='StockAlert',
        ),
    ]
