# Generated by Django 6.1 on 2026-09-06 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0007_remove_stockalert_unique_stock_alert_per_figure_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentual de desconto sobre o preço. Ex.: 10 = 10% OFF.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto (%)'),
        ),
    ]
