# Generated by Django 6.1 on 2026-09-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0008_figure_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, default=30, max_digits=5, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='length_cm',
            field=models.DecimalField(decimal_places=1, default=15, max_digits=5, verbose_name='Comprimento (cm)'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='width_cm',
            field=models.DecimalField(decimal_places=1, default=15, max_digits=5, verbose_name='Largura (cm)'),
        ),
    ]
