# Generated by Django 6.1 on 2026-09-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0009_alter_figure_height_cm_alter_figure_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='is_new_release',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Lançamento'),
        ),
    ]
