# Generated by Django 6.1 on 2026-09-08 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_move_stockalert_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettercampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Campanha', 'verbose_name_plural': 'Campanhas'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['email'], 'verbose_name': 'Assinante', 'verbose_name_plural': 'Assinantes'},
        ),
        migrations.AlterModelOptions(
            name='stockalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
    ]
