# Generated by Django 6.1 on 2026-08-06 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Registro Ativo')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('logo', models.ImageField(upload_to='website/', verbose_name='Logo')),
                ('favicon', models.ImageField(upload_to='website/', verbose_name='Favicon')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('about', models.TextField(verbose_name='Sobre')),
                ('privacy_policy', models.TextField(verbose_name='Política de Privacidade')),
                ('terms', models.TextField(blank=True, verbose_name='Termos de Uso')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
            },
        ),
    ]
