# Generated by Django 6.1 on 2026-08-11 12:45

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='website/banners/', validators=[core.validators.validate_image_size], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='website',
            name='favicon',
            field=models.ImageField(upload_to='website/', validators=[core.validators.validate_image_size], verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='website',
            name='logo',
            field=models.ImageField(upload_to='website/', validators=[core.validators.validate_image_size], verbose_name='Logo'),
        ),
    ]
