# Generated by Django 6.1 on 2026-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_banner_image_alter_website_favicon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Configuração do Site', 'verbose_name_plural': 'Configurações do Site'},
        ),
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.CharField(blank=True, help_text='Texto curto usado no footer e como meta description nas buscas do Google (máx. 160 caracteres).', max_length=160, verbose_name='Descrição (SEO)'),
        ),
    ]
