# Generated by Django 6.1 on 2026-08-11 13:56

import django.db.models.deletion
from django.db import migrations, models


def assign_banners_to_website(apps, schema_editor):
    Banner = apps.get_model("website", "Banner")
    Website = apps.get_model("website", "Website")
    website = Website.objects.order_by("pk").first()
    if website:
        Banner.objects.filter(website__isnull=True).update(website_id=website.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_website_options_website_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order'], 'verbose_name': 'Banner do Site', 'verbose_name_plural': 'Banners do Site'},
        ),
        migrations.AddField(
            model_name='banner',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='website.website', verbose_name='Website'),
        ),
        migrations.RunPython(assign_banners_to_website, migrations.RunPython.noop),
    ]
