# Generated by Django 6.1 on 2026-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_banner_options_banner_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='origin_zip_code',
            field=models.CharField(blank=True, help_text='CEP de onde as encomendas são postadas (usado no cálculo de frete).', max_length=9, verbose_name='CEP de Origem'),
        ),
        migrations.AlterField(
            model_name='website',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Título do Site'),
        ),
    ]
