# Generated by Django 6.1 on 2026-09-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_website_origin_zip_code_alter_website_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='google_analytics',
            field=models.TextField(blank=True, help_text='Cole o snippet completo fornecido pelo Google Analytics (tags <script>...</script>).', verbose_name='Script Google Analytics'),
        ),
        migrations.AddField(
            model_name='website',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Separadas por vírgula. Ex.: action figure, colecionáveis, bonecos importados.', verbose_name='Palavras-chave (SEO)'),
        ),
        migrations.AddField(
            model_name='website',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter / X'),
        ),
    ]
