# Generated by Django 6.1 on 2026-09-08 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_website_google_analytics_website_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='theme_background',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o padrão (#0C0A09).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Fundo'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_border',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o padrão (#44403C).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Bordas'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_buttons',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o dourado padrão.', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Botões / dourado'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_danger',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o padrão (#f87171).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Erro (vermelho)'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_hover',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o padrão.', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Hover dos botões'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_info',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o padrão (#60a5fa).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Informação (azul)'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_muted',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o padrão (#A8A29E).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Texto secundário'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_navbar',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o padrão translúcido.', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Barra de navegação'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_success',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o padrão (#34d399).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Sucesso (verde)'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_surface',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o padrão (#1C1917).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Superfícies (cards)'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_text',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o padrão (#F5F3F0).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_warning',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o padrão (#fbbf24).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Alerta (âmbar)'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme_whatsapp',
            field=models.CharField(blank=True, default='', help_text='Em branco mantém o verde padrão (#25D366).', max_length=7, validators=[django.core.validators.RegexValidator(message='Use o formato hexadecimal, ex.: #EAC979.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Botão WhatsApp'),
        ),
    ]
