# Generated by Django 6.1 on 2026-09-08 19:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_theme_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='website/', validators=[core.validators.validate_image_size], verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='website',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='website/', validators=[core.validators.validate_image_size], verbose_name='Logo'),
        ),
    ]
