# Generated by Django 6.1 on 2026-09-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_website_logo_favicon_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Tagline exibida no título da aba da página inicial. Ex.: O melhor site de action figures.', max_length=255, verbose_name='Subtítulo (marca)'),
        ),
    ]
